version: "3"
services:
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

networks:
  common:
    driver: bridge
